models/Category.php
<?php

namespace app\models;

class Category extends \yii\db\ActiveRecord
{
    const NAME_MIN_LENGTH = 3;
}

controllers/CartController.php
<?php

namespace app\controllers;

class CartController extends \yii\web\Controller
{
    public function actionJson()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $response = \Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $qty = intval(trim(\Yii::$app->request->get('qty'))) ?: null;
        $catId = trim(\Yii::$app->request->get('catId'));
        $cartModel = new \app\models\CartModel;
        if ($catId && is_numeric($catId)) {
            $cartModel->update($catId, $qty);
        }

        $response->data = $cartModel->get();
    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

class CategoryController extends \yii\web\Controller
{
    public function actionSearch()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }

        \Yii::$app->view->title = 'Поиск';

        return $this->render('search', [
            'nameMinLength' => \app\models\Category::NAME_MIN_LENGTH,
        ]);
    }
    public function actionSearchJson()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $response = \Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        $name = trim(\Yii::$app->request->get('name'));
        if (strlen($name) < 3) {
            return;
        }

        $catModel = new \app\models\Category;
        $query = $catModel->find();
        $names = (new \app\models\CategoryModel())->shuffle($name);
        $query->andWhere(['or like', 'name', $names]);
        $query->andWhere(['>=', 'qtyTotal', 1]);
        $response->data = $query->limit(1000)->all();
    }
}

views/category/search.php
<?php
$jsFile = 'js/category.js';
$this->registerJsFile(
	$jsFile.'?'.filemtime(\Yii::$app->basePath.'/web/'.$jsFile)
    ,['depends' => [\yii\web\JqueryAsset::className()]]
    // ,['position' => yii\web\View::POS_LOAD]
 );

$js = '';
$js .= sprintf(
    'urlSearch = "%s"; nameMinLength = "%s";',
    \yii\helpers\BaseUrl::toRoute(['category/search-json']),
    $nameMinLength
);
$js .= sprintf(
    'urlCart = "%s";',
    \yii\helpers\BaseUrl::toRoute(['cart/json'])
);
$js .= sprintf(
    'urlCheckout = "%s";',
    \yii\helpers\BaseUrl::toRoute(['checkout/ajax'])
);
$js .= sprintf(
    'urlOrder = "%s";',
    \yii\helpers\BaseUrl::toRoute(['checkout/order'])
);
$js .= 'cartRender()';
$this->registerJs($js);

?>
<div class="row" id="search">
	<div class="col-8 col-sm-8" id="searchForm">
		<input type=text id="catName">
		<div id="field"></div>
		<div id="result"></div>
	</div>
	<div class="col-4 col-sm-4">
		<div id="cart"></div>
	</div>
</div>
<div id="checkout"></div>