models/Product.php
<?php

namespace app\models;

class Product extends \yii\db\ActiveRecord
{
    const STATE_ACTIVE  = 1;
    const STATE_DISABLE = 2;
    const STATE_SKIP    = 3;

	/**
	* id
	* catId
	* fileId
	* supplierId
	* state
	* artikul
	* name
	* price
    * qty
    * createdAt
	* updatedAt
	**/
	public function getCategory()
	{
		return $this->hasOne(Category::className(), ['id' => 'catId']);
	}
}

controllers/ProductController.php
<?php

namespace app\controllers;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        \Yii::$app->view->title = 'Товары';

        $productModel = new \app\models\ProductModel;
        $supplier = null;
        $conditions = [];

        $supplierId = (int)\Yii::$app->request->get('supplierId');
        if ($supplierId) {
            $supplier = \app\models\Supplier::findOne($supplierId);
        }
        if ($supplier) {
            $conditions['supplierId'] = $supplier->id;
            \Yii::$app->view->title .= ' - Поставщик "' . \yii\helpers\Html::encode($supplier->name) . '"';
        } else {
            $supplierId = null;
        }

        $catId = \Yii::$app->request->get('catId');
        if ($catId) {
            $cat = \app\models\Category::findOne((int)$catId);
        } elseif ($catId === '0') {
            $conditions['catId'] = 0;
            \Yii::$app->view->title .= ' - Без категорий';
        }
        if ($cat) {
            $conditions['catId'] = $cat->id;
            \Yii::$app->view->title .= ' - Категория "' . \yii\helpers\Html::encode($cat->name) . '"';
        } else {
            $catId = null;
        }

        $query = (new \yii\db\Query())
            ->select([
                'product.*',
                'categoryName' => 'category.name',
                'supplierName' => 'supplier.name'
            ])
            ->from(\app\models\Product::tableName())
            ->leftJoin(\app\models\Category::tableName(), 'category.id = product.catId')
            ->leftJoin(\app\models\Supplier::tableName(), 'supplier.id = product.supplierId')
            ->where($conditions)
        ;

        return $this->render('list', [
            'query' => $query,
            'productModel' => $productModel,
            'supplierId' => $supplierId,
            'suppliers' => \app\models\Supplier::find()->all(),
            'catId' => $catId,
        ]);
    }
    
    public function error500()
    {
        \Yii::$app->response->setStatusCode(500);
    }

    public function actionSetCatByName()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $response = \Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
        //для like-запроса слова д.б. всегда окружены пробелами
        // $catName = ' ' + $catName + ' ';
        
        $productId = (int)\Yii::$app->request->post('productId');
        $product = \app\models\Product::findOne($productId);
        if (!$product) {
            return $this->error500();
        }
        $oldCategoryId = $product->catId;

        $catName = trim(\Yii::$app->request->post('catName'));
        if (!$catName) {
            $product->catId = null;
            $product->save();
            if ($oldCategoryId) {
                $category = \app\models\CategorySupplierArtikul::findOne([
                    'categoryId' => $oldCategoryId,
                    'supplierId' => $product->supplierId,
                ]);
                $category && $category->delete();
            }
            return $response->data = ['categoryId' => 0, 'categoryName' => ''];
        }
        
        $cat = \app\models\Category::findOne(['name' => $catName]);
        if (!$cat) {
            $cat = new \app\models\Category;
            $cat->name = $catName;
            $cat->save();
        }
        
        $product->catId = $cat->id;
        $product->save();

        \app\models\CategorySupplierArtikulModel::update($product->artikul, $product->supplierId, $product->catId, $oldCategoryId);
        $categoryModel = new \app\models\CategoryModel;
        $categoryModel->setStat($product->catId);
        $categoryModel->setStat($oldCategoryId);

        return $response->data = ['categoryId' => $product->catId, 'categoryName' => $cat->name];
    }
}

views/product/list.php
<?php
$jsFile = 'js/category.js';
$this->registerJsFile(
    $jsFile.'?'.filemtime(\Yii::$app->basePath.'/web/'.$jsFile)
    ,['depends' => [\yii\web\JqueryAsset::className()]]
    // ,['position' => yii\web\View::POS_LOAD]
 );

$js .= sprintf(
    'urls.setCatNameSearch("%s");',
    \yii\helpers\BaseUrl::toRoute(['category/search-json'])
);
$this->registerJs($js);

$columns = [];
$columns[] = ['class' => 'yii\grid\SerialColumn'];

if (!$supplierId) {
    $columns[] = [
    	'attribute' => ($attr = 'supplierName'),
    	'label' => $productModel->attributeLabels()[$attr],
        'format' => 'raw',
        'value' => function ($data) {
            $img = \yii\helpers\BaseHtml::tag('img', null, ['src' => '/img/search.png', 'width' => 14]);
            return
                \yii\helpers\BaseHtml::tag('a', $img, [
                    'href' => \yii\helpers\BaseUrl::toRoute(['product/index', 'supplierId' => $data['supplierId']]),
                ])
                .' '.
                \yii\helpers\BaseHtml::tag('span', $data['supplierName'])
                ;
        },
    ];
}

if (!$catId) {
//    $spanCatName = '<span style="border-bottom: 1px dotted; cursor: pointer;" onClick="renderCatNameInput({productId})">{catName}</span>';
//    die(str_replace(['{productId}', '{catName}'], [123, 456], $spanCatName));
    $columns[] = [
        'attribute' => ($attr = 'categoryName'),
        'label' => $productModel->attributeLabels()[$attr],
        'format' => 'raw',
        'value' => function ($data) {
            $img = \yii\helpers\BaseHtml::tag('img', null, ['src' => '/img/search.png', 'width' => 14]);
            return \yii\helpers\BaseHtml::tag(
                'div',
                \yii\helpers\BaseHtml::tag(
                    'span',
                    \yii\helpers\BaseHtml::tag('a', $img, [
                        'href' => \yii\helpers\BaseUrl::toRoute(['product/index', 'catId' => $data['catId']]),
                    ])
                    .' '.
                    \yii\helpers\BaseHtml::tag(
                        'span',

                        ($data['categoryName'] ?: '<span class="not-set">(не задано)</span>'),

                        [
                            'class' => 'categoryInput',
                            'onClick' => 'renderCatNameInput('.$data['id'].', \''.$data['categoryName'].'\')',
                        ]
                    ),
                    [
                        'id' => 'spanCatIdForProduct'.$data['id'],
                    ]
                )
                , [
                    'class' => 'productCategoryName',
                ]
            );
        },
    ];
}

$js = '
function renderCatNameInput(productId, catName)
{
    form = "<form id=\'productCatNameForm\' onSubmit=\'productCatUpdate(this); return false;\'>    "
+"<input type=hidden name=\'productId\' value=\'"+productId+"\'>"
+"<input type=text class=catName name=\'catName\' value=\'"+catName+"\' autofocus productId=\'"+productId+"\'>"

+"</form><div class=productCategoryNameHint productId=\'"+productId+"\'></div>";
    document.getElementById("spanCatIdForProduct"+productId).innerHTML=form;

        
}
function productCatUpdate(obj)
{
    productId = obj.productId.value;
    span = document.getElementById("spanCatIdForProduct"+productId);
    span.innerHTML="сохранение...";
    urlSearch = "'. \yii\helpers\BaseUrl::toRoute(['product/index']) .'";

    var data = $(obj).serialize();
    $.ajax({
    url: "'.\yii\helpers\Url::to(['product/set-cat-by-name']).'",
    type: "POST",
    data: data,
    success: function(res){
        categoryId = res.categoryId;
        categoryName = res.categoryName;

        searchButton = "<a href=\'"+urlSearch+"?catId="+categoryId+"\'><img src=\'/img/search.png\' width=14></a>";
        
        span.innerHTML = searchButton + " <span class=categoryInput onClick=\"renderCatNameInput("+productId+", \'"+categoryName+"\')\">"+(categoryId ? categoryName : "<span class=\"not-set\">(не задано)</span>")+"</span>";
    },
    error: function(){
        span.innerHTML ="<span class=categoryInput onClick=\"renderCatNameInput("+productId+", \'\')\">ошибка!</span>";
    }
    });
    
}
';

$columns = array_merge($columns, [
    [
        'attribute' => ($attr = 'artikul'),
    	'label' => $productModel->attributeLabels()[$attr],
    ],
    [
    	'attribute' => ($attr = 'name'),
    	'label' => $productModel->attributeLabels()[$attr],
    ],
    [
    	'attribute' => ($attr = 'price'),
    	'label' => $productModel->attributeLabels()[$attr],
    ],
    [
    	'attribute' => ($attr = 'qty'),
    	'label' => $productModel->attributeLabels()[$attr],
    ],
]);

//$model = \app\models\ProductCatForm;
?>
<div>
    <h1><?= \yii\helpers\Html::encode($this->title) ?></h1>

        <div class="row" id="productsList">
            <?= \yii\helpers\Html::tag('script', $js) ?>
			<?= \yii\grid\GridView::widget([
			    'dataProvider' => new \yii\data\ActiveDataProvider([
				    'query' => $query,
				    'pagination' => [
				        'pageSize' => 150,
				    ],
				]),
			    'columns' => $columns,
			]); ?>
        </div>

</div>