models/Supplier.php
<?php

namespace app\models;

class Supplier extends \yii\db\ActiveRecord
{
    private $priceFile;

    public function getPriceFile()
    {
        if (null === $this->priceFile) {
            $this->priceFile = new PriceFile;
        }
        return $this->priceFile;
    }
    
    public function add(\app\models\SupplierForm $form): bool
    {
        $this->name         = $form->name;
        $this->delivery     = $form->delivery;
        $this->deliveryTime = $form->deliveryTime;
        $this->deliveryCost = $form->deliveryCost;
        $this->deliveryFree = $form->deliveryFree;
        $this->pickup       = $form->pickup;
        $this->discount     = $form->discount;
        $this->addresses    = $form->addresses;
        $this->notes        = $form->notes;

        return $this->save();
    }

    public static function get(int $supplierId)
    {
        return self::findOne(['id' => $supplierId]);
    }

    public static function getName(int $supplierId)
    {
        return self::get($supplierId)['name'];
    }

    public static function getDiscount(int $supplierId)
    {
        return self::get($supplierId)['discount'];
    }

    public function hasFileConfig()
    {
        if (   null !== $this->fileColumnArtikul
            && null !== $this->fileColumnName
            && null !== $this->fileColumnPrice
            && null !== $this->fileColumnQty
            && null !== $this->fileLineDataStart
        ) {
            return true;
        }
        return false;
    }

    public function getFileConfig()
    {
        return [
            'fileColumnArtikul' => $this->fileColumnArtikul,
            'fileColumnName'    => $this->fileColumnName,
            'fileColumnPrice'   => $this->fileColumnPrice,
            'fileColumnQty'     => $this->fileColumnQty,
            'fileLineDataStart' => $this->fileLineDataStart,
            'fileQtyDefault'    => $this->fileQtyDefault,
        ];
    }

    public static function getByName($name)
    {
        return self::findOne(['name' => $name]);
    }

    public function list()
    {
        $sort = new \yii\data\Sort([
            'attributes' => [
                'id',
                'name',
                'delivery',
                'deliveryTime',
                'deliveryCost',
                'deliveryFree',
                'pickup',
                'discount',

                'created_at',
                'updated_at',
            ],
        ]);

        return new \yii\data\ActiveDataProvider([
            'query' => self::find()->orderBy($sort->orders),
            // 'query' => self::find()->joinWith('products')->orderBy($sort->orders),
            'sort' => $sort,
        ]);
    }

    // public function getProducts()
    // {
    //     return $this->hasOne(Product::className(), ['supplierId' => 'id']);
    // }
}

models/SupplierForm.php
<?php

namespace app\models;

class SupplierForm extends \yii\base\Model
{
    public $id;
    public $name;
    public $delivery;
    public $deliveryTime;
    public $deliveryCost;
    public $deliveryFree;
    public $pickup;
    public $discount;
    public $addresses;
    public $notes;

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'isNameUnique'],
            [['delivery', 'deliveryTime', 'deliveryCost', 'deliveryFree', 'pickup', 'discount', 'addresses', 'notes'], 'trim'],
        ];
    }

    public function isNameUnique($attribute, $params, $validator)
    {
        $name = $this->$attribute;
        $supplier = \app\models\Supplier::getByName($name);
        if ($supplier && $supplier->id != $this->id) {
            $this->addError($attribute, 'Поставщик с наименованием "' . $name . '" уже существует');
        }
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Наименование',
            'delivery' => 'Доставка',
            'deliveryTime' => 'Срок доставки, дней',
            'deliveryCost' => 'Стоимость доставки, рублей',
            'deliveryFree' => 'Бесплатная доставка при сумме заказа от, рублей',
            'pickup' => 'Самовывоз',
            'discount' => 'Скидка, %',
            'addresses' => 'Адреса',
            'notes' => 'Заметки',

            'createdAt' => 'Создано',
            'updatedAt' => 'Изменено',
        ];
    }
}

controllers/SupplierController.php
<?php

namespace app\controllers;

class SupplierController extends \yii\web\Controller
{
    public function actionImport()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $result = $this->fileCanUse();
        if (!is_array($result)) {
            return $result;
        }
        [$fileId, $file, $fileModel] = $result;

        //если файл ещё не готов для импорта или всё готово для импорта, но не получена команде об импорте, то отправим на страницу подтверждения
        if (!$file->isReady() || !\Yii::$app->request->get('confirmed')) {
            return \Yii::$app->getResponse()->redirect(['supplier/price-confirm', 'fileId' => $fileId]);
        }

        $productModel = new \app\models\ProductModel;
        if (!$productModel->importFile($file)) {
            return $this->render('priceImport', ['result' => 'importFail']);
        }
        // $file->status = $file::STATUS_IMPORTED;
        $file->save();

        return $this->render('priceImport', [
            'result' => 'importSuccess',
            'supplierId' => $file->supplierId,
            'importStat' => $file->getInfo()['stat'],
        ]);
    }

    public function actionPriceConfirm()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $result = $this->fileCanUse();
        if (!is_array($result)) {
            return $result;
        }
        [$fileId, $file, $fileModel] = $result;

        if (!$file->isLearned()) {
            return \Yii::$app->getResponse()->redirect(['supplier/price-learn', 'fileId' => $fileId]);
        }

        if (\Yii::$app->request->get('confirmed')) {
            $file->status = $file::STATUS_READY;
            $file->save();

            $supplier = (new \app\models\Supplier)->get($file->supplierId);
            $supplier->fileColumnArtikul = $file->fileColumnArtikul;
            $supplier->fileColumnName    = $file->fileColumnName;
            $supplier->fileColumnPrice   = $file->fileColumnPrice;
            $supplier->fileColumnQty     = $file->fileColumnQty;
            $supplier->fileLineDataStart = $file->fileLineDataStart;
            $supplier->fileQtyDefault    = $file->fileQtyDefault;
            $supplier->save();

            return \Yii::$app->getResponse()->redirect(['supplier/import', 'fileId' => $fileId, 'confirmed' => 1]);
        }

        $i=-1;
        $lastViewLine = 49+$file->fileLineDataStart;
        $rows = [];
        foreach ($file->getData() as $row) {
            if (++$i > $lastViewLine) {
                break;
            }
            if ($i < $file->fileLineDataStart) {
                continue;
            }
            $rows[] = $row;
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rows,
            'pagination' => [
                'pageSize' => 20000,
            ],
        ]);

        $columns = [
            ['class' => 'yii\grid\SerialColumn'],
            ['label' => 'Наименование', 'value' => (string)$file->fileColumnName],
            ['label' => 'Артикул', 'value' => (string)$file->fileColumnArtikul],
            ['label' => 'Цена', 'value' => (string)$file->fileColumnPrice],
            ['label' => 'Кол-во', 'value' => (string)$file->fileColumnQty],
        ];

        return $this->render('priceConfirm', [
            'dataProvider' => $dataProvider,
            'columns' => $columns,
            'fileId' => $fileId,
            'fileQtyDefault' => [
                'label' => (new \app\models\PriceLearnForm)->attributeLabels()['fileQtyDefault'],
                'value' => (string)$file->fileQtyDefault,
            ],
        ]);
    }

    public function actionPriceLearn()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $result = $this->fileCanUse();
        if (!is_array($result)) {
            return $result;
        }
        [$fileId, $file, $fileModel] = $result;

        $form = new \app\models\PriceLearnForm;
        if (\Yii::$app->request->getIsGet()) {
            $form->fileColumnArtikul = $file->fileColumnArtikul;
            $form->fileColumnName    = $file->fileColumnName;
            $form->fileColumnPrice   = $file->fileColumnPrice;
            $form->fileColumnQty     = $file->fileColumnQty;
            $form->fileLineDataStart = $file->fileLineDataStart;
            $form->fileQtyDefault    = $file->fileQtyDefault;
        }

        if ($form->load(\Yii::$app->request->post()) && $form->validate() && $form->isValsUnique()) {
            $file->setConfig([
                'fileColumnArtikul' => $form->fileColumnArtikul,
                'fileColumnName'    => $form->fileColumnName,
                'fileColumnPrice'   => $form->fileColumnPrice,
                'fileColumnQty'     => $form->fileColumnQty,
                'fileLineDataStart' => $form->fileLineDataStart,
                'fileQtyDefault'    => $form->fileQtyDefault,
            ]);
            $file->status = $file::STATUS_NEED_CONFIRM;
            $file->save();

            return \Yii::$app->getResponse()->redirect(['supplier/price-confirm', 'fileId' => $fileId]);
        }

        $i=0;
        $rows = [];
        foreach ($file->getData() as $row) {
            if (++$i > 50) {
                break;
            }
            $rows[] = $row;
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rows,
            'pagination' => [
                'pageSize' => 20000,
            ],
        ]);

        $columns[] = ['class' => 'yii\grid\SerialColumn'];
        for ($i=0; $i<count($rows[0]); $i++) {
            $columns[] = (string)$i;
        }

        return $this->render('priceLearn', [
            'dataProvider' => $dataProvider,
            'columns' => $columns,
            'model' => $form,
        ]);
    }

    public function actionPriceUpload()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $renderData = [];
        $supplierModel = new \app\models\Supplier();
        $form = new \app\models\SupplierPriceUpload();

        $isFormValid = false;
        if (
            $form->load(\Yii::$app->request->post())
            && $form->validate()
            && $supplierModel->get($form->supplierId)
            && $form->price = \yii\web\UploadedFile::getInstance($form, 'price')
        ) {
            $isFormValid = true;
        }

        if ($isFormValid && !$form->isFileValid('price', $form->price)) {
            $fileId = $supplierModel->getPriceFile()->priceFileAdd($form);

            $supplier = $supplierModel->get($form->supplierId);
            if ($supplier->hasFileConfig()) {
                $file = $supplierModel->getPriceFile()->get($fileId);
                $file->setConfig($supplier->getFileConfig());
                $file->status = $file::STATUS_NEED_CONFIRM;
                $file->save();

                return \Yii::$app->getResponse()->redirect(['supplier/price-confirm', 'fileId' => $fileId]);
            }
            
            return \Yii::$app->getResponse()->redirect(['supplier/price-learn', 'fileId' => $fileId]);
        }

        $renderData['model'] = $form;
        $renderData['suppliers'] = \yii\helpers\ArrayHelper::map($supplierModel::find()->all(), 'id', 'name');
        return $this->render('priceUpload', $renderData);
    }

    public function actionIndex()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $form = new \app\models\SupplierForm();
        $supplier = new \app\models\Supplier();
        return $this->render('list', [
            'suppliers' => $supplier->list(),
            'form' => $form,
        ]);
    }

    public function actionAdd()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $form = new \app\models\SupplierForm();
        $supplierModel = new \app\models\Supplier();

        if ($form->load(\Yii::$app->request->post()) && $form->validate() && $supplierModel->add($form)) {
            ;
            \Yii::$app->session->setFlash('supplierAdded');
            \Yii::$app->session->setFlash('supplierName', $form->name);

            return $this->refresh();
        }

        return $this->render('form', [
            'model' => $form,
        ]);
    }

    public function actionEdit()
    {
        if (!\app\models\Auth::mustBeLoggedIn()) {
            return;
        }
        
        $form = new \app\models\SupplierForm();
        $supplierModel = new \app\models\Supplier();

        $supplierId = (int)\Yii::$app->request->get('supplierId');
        if (!$supplierId) {
            return $this->render('error', ['error' => 'Не передан ID поставщика.']);
        }
        $supplier = $supplierModel->get($supplierId);
        if (!$supplier) {
            return $this->render('error', ['error' => 'Поставщик с ID '.$supplierId.' не найден.']);
        }

        $form->id = $supplier->id;

        if (\Yii::$app->request->getIsGet()) {
            $form->name         = $supplier->name;
            $form->delivery     = $supplier->delivery;
            $form->deliveryTime = $supplier->deliveryTime;
            $form->deliveryCost = $supplier->deliveryCost;
            $form->deliveryFree = $supplier->deliveryFree;
            $form->pickup       = $supplier->pickup;
            $form->discount     = $supplier->discount;
            $form->addresses    = $supplier->addresses;
            $form->notes        = $supplier->notes;
        }

        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            
            $supplier->name         = $form->name;
            $supplier->delivery     = $form->delivery;
            $supplier->deliveryTime = $form->deliveryTime;
            $supplier->deliveryCost = $form->deliveryCost;

views/supplier/error.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\supplierForm */

use yii\helpers\Html;

$this->title = 'Ошибка';
$this->params['breadcrumbs'][] = $this->title;
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
    	<?= $error ?>
    </div>
</div>

views/supplier/form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Поставщик';
$this->params['breadcrumbs'][] = $this->title;

$yesNo = [0 => 'нет', 1 => 'да'];
$numberFormat = ['type' => 'number', 'min' => 0, 'step' => 1];
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('supplierAdded')): ?>

        <div class="alert alert-success">
            Поставщик <b><?= Html::encode(Yii::$app->session->getFlash('supplierName')) ?></b> успешно добавлен.
        </div>

    <?php endif; ?>

    <?php if (Yii::$app->session->hasFlash('supplierUpdated')): ?>

        <div class="alert alert-success">
            Поставщик <b><?= Html::encode(Yii::$app->session->getFlash('supplierName')) ?></b> успешно обновлён.
        </div>

    <?php endif; ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'supplier-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => false]) ?>

                    <?= $form->field($model, 'delivery')->dropdownList($yesNo); ?>

                    <?= $form->field($model, 'deliveryTime'); ?>

                    <?= $form->field($model, 'deliveryCost')->textInput($numberFormat); ?>

                    <?= $form->field($model, 'deliveryFree')->textInput($numberFormat); ?>

                    <?= $form->field($model, 'pickup')->dropdownList($yesNo); ?>

                    <?= $form->field($model, 'discount'); ?>

                    <?= $form->field($model, 'addresses')->textarea(); ?>

                    <?= $form->field($model, 'notes')->textarea(); ?>

                    <div class="form-group">
                        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'supplier-button']) ?>
                    </div>

                <?php $form->end(); ?>

            </div>
        </div>

</div>

views/supplier/list.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\supplierForm */

use yii\helpers\Html;

$this->title = 'Поставщики';
$this->params['breadcrumbs'][] = $this->title;
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="row">

			<?= \yii\grid\GridView::widget([
			    'dataProvider' => $suppliers,
            // 'pagination' => [
            //     'pageSize' => 20000,
            // ],
			    'columns' => [
			        ['class' => 'yii\grid\SerialColumn'],
			        // 'id',
			        [
			        	'attribute' => 'id',
						'format' => 'raw',
					    'value' => function ($data) {
					        return Html::a(Html::encode($data->id),['supplier/edit', 'supplierId' => $data->id]);
					    },
			        ],
			        [
			        	'attribute' => ($attr = 'id'),
			        	'label' => 'Наименования',
						'format' => 'raw',
					    'value' => function ($data) {
					        return Html::a('все',['product/index', 'supplierId' => $data->id, 'catId' => ''])
					        	. ' | ' . Html::a('без категорий',['product/index', 'supplierId' => $data->id, 'catId' => 0]);
					    },
			        ],
			        // [
			        // 	'attribute' => ($attr = 'productsQty'),
			        // 	'label' => 'Наименований',
			        // 	'format' => 'number',
			        // ],
			        // [
			        // 	'attribute' => ($attr = 'productsSkippedQty'),
			        // 	'label' => 'Пропущенных наименований',
			        // 	'format' => 'number',
			        // ],
			        // [
			        // 	'attribute' => ($attr = 'uploadDate'),
			        // 	'label' => 'Дата последней загрузки',
			        // 	'format' => 'date',
			        // ],
			        // [
			        // 	'attribute' => ($attr = \app\models\Product::className().'.name'),
			        // 	'label' => 'Дата последней загрузки',
			        // 	'format' => 'date',
			        // ],
			        [
			        	'attribute' => ($attr = 'name'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'delivery'),
			        	'label' => $form->attributeLabels()[$attr],
			        	'format' => 'boolean',
			        ],
			        [
			        	'attribute' => ($attr = 'deliveryTime'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'deliveryCost'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'deliveryFree'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'pickup'),
			        	'label' => $form->attributeLabels()[$attr],
			        	'format' => 'boolean',
			        ],
			        [
			        	'attribute' => ($attr = 'discount'),
			        	'label' => $form->attributeLabels()[$attr],
			        	'format' => 'decimal',
			        ],
			        [
			        	'attribute' => ($attr = 'addresses'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'notes'),
			        	'label' => $form->attributeLabels()[$attr],
			        ],
			        [
			        	'attribute' => ($attr = 'createdAt'),
			        	'label' => $form->attributeLabels()[$attr],
			        	'format' => ['date', 'php:d.m.Y']
			        ],
			        [
			        	'attribute' => ($attr = 'updatedAt'),
			        	'label' => $form->attributeLabels()[$attr],
			        	'format' => ['date', 'php:d.m.Y']
			        ],
			    ],
			]); ?>
            
        </div>

</div>

views/supplier/priceConfirm.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Прайс - Подтверждение';
$this->params['breadcrumbs'][] = $this->title;

$inputVals = [];
foreach ($columns as $column) {
    if (is_string($column) || is_numeric($column)) {
        $inputVals[] = $column;
    }
}
//array_fill
$lineNums = [];
for ($i=1; $i<=50; $i++) {
    $lineNums[] = $i;
}
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="row">
            <div class="col-lg-5">
                    <div class="form-group">

                        <?= Html::beginForm(['/supplier/price-learn', 'fileId' => $fileId], 'get', ['style' => 'display: inline;']) ?>
                        <?= Html::submitButton('Переобучить', ['class' => 'btn btn-warning', 'name' => 'supplier-button']) ?>
                        <?= Html::endForm() ?>

                        <?= Html::beginForm(['/supplier/price-confirm', 'fileId' => $fileId], 'get', ['style' => 'display: inline;']) ?>
                        <?= Html::submitButton('Всё верно, импортировать', ['class' => 'btn btn-success', 'name' => 'confirmed', 'value' => 1]) ?>
                        <?= Html::endForm() ?>

                    </div>

            </div>
        </div>

        <div class="row">
            <?= $fileQtyDefault['label'] ?>: <?= $fileQtyDefault['value'] ?: 'не задано' ?>.
            <p>
        </div>
        <div class="row">
                <?= \yii\grid\GridView::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => $columns,
                        ]);
                ?>
        </div>

</div>

views/supplier/priceImport.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Прайс - Завершение импорта';
$this->params['breadcrumbs'][] = $this->title;
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="row">
            <?php if ($result == 'importSuccess'): ?>
                <div class="alert alert-success">
                    Файл успешно импортирован.
                </div>
                <?= $importStat['total'] ?>    - Записей всего<br>
                <?= $importStat['imported'] ?> - Импортировано<br>
                <?= $importStat['skipped']?>   - Пропущено <p>
            <?php endif; ?>

            <?php if ($result == 'importFail'): ?>
                <div class="alert alert-warning">
                    Ошибка в процессе импорта файла.
                </div>
            <?php endif; ?>

            <?php if ($result == 'alreadyImported'): ?>
                <div class="alert alert-warning">
                    Файл уже был импортирован ранее.
                </div>
                <?= $importStat['total'] ?>    - Записей всего<br>
                <?= $importStat['imported'] ?> - Импортировано<br>
                <?= $importStat['skipped']?>   - Пропущено <p>
            <?php endif; ?>
        </div>

        <div class="row">
            <?= Html::a('Показать товары без категории', ['product/index', 'supplierId' => $supplierId, 'catId' => 0])?>
        </div>

</div>

views/supplier/priceLearn.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Прайс - Обучение';
$this->params['breadcrumbs'][] = $this->title;

$inputVals = [];
foreach ($columns as $column) {
    if (is_string($column) || is_numeric($column)) {
        $inputVals[] = $column;
    }
}
//array_fill
$lineNums = [];
for ($i=1; $i<=50; $i++) {
    $lineNums[] = $i;
}
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(); ?>

                    <?= $form->field($model, 'fileColumnArtikul')->dropdownList($inputVals, ['prompt' => 'Укажите номер столбца']) ?>
                    <?= $form->field($model, 'fileColumnName')->dropdownList($inputVals, ['prompt' => 'Укажите номер столбца']) ?>
                    <?= $form->field($model, 'fileColumnPrice')->dropdownList($inputVals, ['prompt' => 'Укажите номер столбца']) ?>
                    <?= $form->field($model, 'fileColumnQty')->dropdownList($inputVals, ['prompt' => 'Укажите номер столбца']) ?>
                    <?= $form->field($model, 'fileLineDataStart')->dropdownList($lineNums, ['prompt' => 'Укажите номер строки']) ?>
                    <?= $form->field($model, 'fileQtyDefault') ?>

                    <div class="form-group">
                        <?= Html::submitButton('Проверить', ['class' => 'btn btn-primary', 'name' => 'supplier-button']) ?>
                    </div>

                <?php $form->end(); ?>

            </div>
        </div>

        <div class="row">
                <?= \yii\grid\GridView::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => $columns,
                        ]);
                ?>
        </div>

</div>

views/supplier/priceUpload.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Прайс - Загрузка';
$this->params['breadcrumbs'][] = $this->title;
?>
<div>
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="row">
            <div class="col-lg-5">

                <p>Загрузите файл в формате <?= implode(', ', $model->extensions) ?>.<!-- Если у вас экселевский файл, 
                выберите "Сохранить как" и во всплывшей форме укажите формат
                csv (разделители запятые). Либо можете воспользоваться любым онлайн-конвертером, например, <a href="#">converter</a>.--></p>

                <?php $form = ActiveForm::begin(['id' => 'supplier-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>

                    <?= $form->field($model, 'supplierId')->dropdownList($suppliers, ['prompt' => 'Выберите']); ?>

                    <?= $form->field($model, 'price')->fileInput() ?>

                    <div class="form-group">
                        <?= Html::submitButton('Загрузить', ['class' => 'btn btn-primary', 'name' => 'supplier-button']) ?>
                    </div>

                <?php $form->end(); ?>

            </div>
        </div>

</div>